site_name: Python Project Poetry

theme:
  name: "material"

plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Index Page: index.md
  - Tutorials: tutorials.md
  - How-To-Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md

repo_url: https://github.com/khosbayar-sorenson/gh-actions-poetry

# to navigate with `/site` content correctly
use_directory_urls: false
