name: Dev

on:
  pull_request_target:
    types: [closed, opened]
    branches:
      - dev

jobs:
  call-testing-pipeline:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      # Run tests here
      - name: Test step
        run: echo "Running tests"
  call-linting-pipeline:
    name: Linting
    runs-on: ubuntu-latest
    needs: call-testing-pipeline
    steps:
      # Run linters here
      - name: Lint step
        run: echo "Running linters"
  call-release-pipeline:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - call-testing-pipeline
      - call-linting-pipeline
    if: github.event.pull_request.merged == true
    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      # Install dependencies and run semantic-release
      - name: Publish new version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pipx install poetry
          poetry install --only semver
          set -o pipefail
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          poetry run semantic-release publish -v DEBUG -D commit_author="github-actions <action@github.com>"
