name: Release

on:
  push:
    branches:
      - main
      - feat/*
  pull_request:
    branches:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      # install poetry
      - name: Install poetry
        run: pipx install poetry

      # update version in pyproject.toml
      - name: Update version in pyproject.toml
        run: |
          export VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          poetry version "${VERSION}"

      # update CHANGELOG.MD
      - name: Update CHANGELOG.MD
        run: |
          export VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          echo -e "## ${VERSION}\n\n$(cat CHANGELOG.MD)" > CHANGELOG.MD

      # commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add pyproject.toml CHANGELOG.MD
          git commit -m "Update version and CHANGELOG.MD for tag ${VERSION}"
          git push origin HEAD:${{ github.ref }}

      # set-up python with cache
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      # install requirements
      - name: Install requirements
        run: poetry install --only semver

      # semantic release
      - name: Python Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -o pipefail
          # Set git details
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          # run semantic-release
          poetry run semantic-release publish -v DEBUG -D commit_author="github-actions <action@github.com>"
