---
name: "Lint PR"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hi
        run: echo "Validate PR title"
# jobs:
#   main:
#     name: Validate PR title
#     runs-on: ubuntu-latest
#     steps:
#       - uses: amannn/action-semantic-pull-request@v5
#         env:
#           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
